unstable_features = true
imports_granularity = "Crate"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
use_field_init_shorthand = true
use_try_shorthand = true
wrap_comments = true
