[package]
name = "cache-table"
version = "0.0.0"
authors = ["Daniel Mack"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
poker = { path = ".." }
phf_codegen = "0.8"
